### ISSUE TITLE
Add `sort_dicts` option

### ISSUE THREAD

**Issue by joaonc** [joaonc/pprintpp2#7]
From issue here: https://github.com/wolever/pprintpp/issues/26
Existing PR here: https://github.com/wolever/pprintpp/pull/27

In python 3.8, the `sort_dicts` option was added ([here](https://docs.python.org/3/library/pprint.html#pprint.PrettyPrinter)) and would be great to add that option in this package as well, not only to maintain drop replacement functionality with `pprint`, but also to add the functionality that argument brings.

**Comment by peter-malcolm-bw** [comment]
Thanks for forking and merging. Have you been able to take ownership of the project PyPi (https://pypi.org/project/pprintpp/) as part of the fork? It looks like the latest release is still 0.4.0 . Or is the plan to release under pprintpp2 or pprintppp ;) ?

**Comment by joaonc** [comment]
Hi @peter-malcolm-bw , I contacted @wolever, `pprintpp`'s creator, to see if I can be added as admin in his project.  If yes, then I'll merge back the changes done here and `pprintpp` will live on.  Otherwise I'll start `pprintpp2` as a replacement, which I've noticed is a common practice with open source projects that continue where others left off.   Let's see what happens.
